"""agregar credenciales a user tenants

Revision ID: 672515f72708
Revises: a4e3834134ff
Create Date: 2026-08-19 17:55:21.765025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672515f72708'
down_revision: Union[str, Sequence[str], None] = 'a4e3834134ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column(
        'user_tenants',
        sa.Column(
            'email',
            sa.String(length=255),
            nullable=True
        ),
        schema='users_api'
    )

    op.add_column(
        'user_tenants',
        sa.Column(
            'password',
            sa.String(length=200),
            nullable=True
        ),
        schema='users_api'
    )

    op.add_column(
        'user_tenants',
        sa.Column(
            'phone',
            sa.String(length=20),
            nullable=True
        ),
        schema='users_api'
    )

    op.add_column(
        'user_tenants',
        sa.Column(
            'activation_token',
            sa.String(length=200),
            nullable=True
        ),
        schema='users_api'
    )


    # Migrar usuarios actuales al tenant demo
    op.execute(
        """
        UPDATE users_api.user_tenants ut
        SET
            email = u.email,
            password = u.password,
            phone = u.phone,
            activation_token = u.activation_token
        FROM users_api.app_users u
        WHERE ut.user_id = u.id
        """
    )


    # Ahora sí obligamos datos
    op.alter_column(
        'user_tenants',
        'email',
        nullable=False,
        schema='users_api'
    )

    op.alter_column(
        'user_tenants',
        'password',
        nullable=False,
        schema='users_api'
    )


    op.create_index(
        'ix_users_api_user_tenants_activation_token',
        'user_tenants',
        ['activation_token'],
        unique=True,
        schema='users_api'
    )

    op.create_index(
        'ix_users_api_user_tenants_email',
        'user_tenants',
        ['email'],
        unique=False,
        schema='users_api'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_user_tenants_email'), table_name='user_tenants', schema='users_api')
    op.drop_index(op.f('ix_users_api_user_tenants_activation_token'), table_name='user_tenants', schema='users_api')
    op.drop_column('user_tenants', 'activation_token', schema='users_api')
    op.drop_column('user_tenants', 'phone', schema='users_api')
    op.drop_column('user_tenants', 'password', schema='users_api')
    op.drop_column('user_tenants', 'email', schema='users_api')
    # ### end Alembic commands ###
