"""create global users for super

Revision ID: 6c5f8a9b21d4
Revises: 01b9e3e9e8f2
Create Date: 2026-08-22

"""

from typing import Sequence, Union

from alembic import op


revision: str = "6c5f8a9b21d4"
down_revision: Union[str, Sequence[str], None] = "01b9e3e9e8f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.execute(
        """
        CREATE TABLE users_api.global_users (
            id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email varchar(255) NOT NULL,
            password_hash varchar(255) NOT NULL,
            is_active boolean NOT NULL DEFAULT true,
            is_superuser boolean NOT NULL DEFAULT true,
            mfa_enabled boolean NOT NULL DEFAULT true,
            mfa_secret_encrypted varchar(512),
            session_id varchar(36),
            last_login_at timestamp,
            last_login_ip varchar(45),
            created_at timestamp NOT NULL,
            created_by varchar(100) NOT NULL,
            created_by_bd varchar(100) DEFAULT USER,
            updated_at timestamp,
            updated_by varchar(100),
            updated_by_bd varchar(100) DEFAULT USER,
            CONSTRAINT ck_global_users_only_super
                CHECK (is_superuser = true),
            CONSTRAINT uq_global_users_session_id
                UNIQUE (session_id)
        );
        """
    )

    op.execute(
        """
        CREATE UNIQUE INDEX uq_global_users_email_lower
        ON users_api.global_users (lower(email));
        """
    )

    op.execute(
        """
        CREATE INDEX ix_global_users_email
        ON users_api.global_users (email);
        """
    )

    op.execute(
        """
        GRANT SELECT, INSERT, UPDATE
        ON TABLE users_api.global_users
        TO users_api_app;
        """
    )

    op.execute(
        """
        GRANT USAGE, SELECT
        ON SEQUENCE users_api.global_users_id_seq
        TO users_api_app;
        """
    )


def downgrade() -> None:

    op.execute(
        """
        REVOKE ALL PRIVILEGES
        ON TABLE users_api.global_users
        FROM users_api_app;
        """
    )

    op.execute(
        """
        DROP TABLE IF EXISTS users_api.global_users;
        """
    )
