"""crear esquema inicial users_api

Revision ID: 9de3efc251f7
Revises: 
Create Date: 2026-08-18 19:52:49.603077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de3efc251f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Crear esquema de la aplicación
    op.execute('CREATE SCHEMA IF NOT EXISTS "users_api"')

    # Crear tabla de usuarios
    op.create_table(
        'app_users',
        sa.Column(
            'id',
            sa.Integer(),
            sa.Identity(always=False, start=1, increment=1),
            nullable=False
        ),
        sa.Column('dni', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=True),
        sa.Column('status', sa.Integer(), nullable=True),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('password', sa.String(length=200), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by', sa.String(length=100), nullable=False),
        sa.Column(
            'created_by_bd',
            sa.String(length=100),
            server_default=sa.text('USER'),
            nullable=True
        ),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('updated_by', sa.String(length=100), nullable=True),
        sa.Column(
            'updated_by_bd',
            sa.String(length=100),
            server_default=sa.text('USER'),
            nullable=True
        ),
        sa.Column(
            'activation_token',
            sa.String(length=200),
            nullable=True
        ),
        sa.PrimaryKeyConstraint('id'),
        schema='users_api'
    )

    # Índices
    op.create_index(
        op.f('ix_users_api_app_users_activation_token'),
        'app_users',
        ['activation_token'],
        unique=True,
        schema='users_api'
    )

    op.create_index(
        op.f('ix_users_api_app_users_dni'),
        'app_users',
        ['dni'],
        unique=True,
        schema='users_api'
    )

    op.create_index(
        op.f('ix_users_api_app_users_email'),
        'app_users',
        ['email'],
        unique=True,
        schema='users_api'
    )

    op.create_index(
        op.f('ix_users_api_app_users_name'),
        'app_users',
        ['name'],
        unique=False,
        schema='users_api'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_app_users_name'), table_name='app_users', schema='users_api')
    op.drop_index(op.f('ix_users_api_app_users_email'), table_name='app_users', schema='users_api')
    op.drop_index(op.f('ix_users_api_app_users_dni'), table_name='app_users', schema='users_api')
    op.drop_index(op.f('ix_users_api_app_users_activation_token'), table_name='app_users', schema='users_api')
    op.drop_table('app_users', schema='users_api')
    # ### end Alembic commands ###
