"""crear modulo de roles y permisos

Revision ID: a4e3834134ff
Revises: 0f44051a723f
Create Date: 2026-08-19 11:08:03.634152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e3834134ff'
down_revision: Union[str, Sequence[str], None] = '0f44051a723f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_by_bd', sa.String(length=100), server_default=sa.text('USER'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by_bd', sa.String(length=100), server_default=sa.text('USER'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_permissions_code'),
    schema='users_api'
    )
    op.create_index(op.f('ix_users_api_permissions_code'), 'permissions', ['code'], unique=True, schema='users_api')
    op.create_table('roles',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_by_bd', sa.String(length=100), server_default=sa.text('USER'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by_bd', sa.String(length=100), server_default=sa.text('USER'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['users_api.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_roles_tenant_code'),
    schema='users_api'
    )
    op.create_index(op.f('ix_users_api_roles_code'), 'roles', ['code'], unique=False, schema='users_api')
    op.create_index(op.f('ix_users_api_roles_tenant_id'), 'roles', ['tenant_id'], unique=False, schema='users_api')
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['users_api.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['users_api.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_role_permission'),
    schema='users_api'
    )
    op.create_index(op.f('ix_users_api_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False, schema='users_api')
    op.create_index(op.f('ix_users_api_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False, schema='users_api')
    op.create_table('user_tenant_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_tenant_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['users_api.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_tenant_id'], ['users_api.user_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_tenant_id', 'role_id', name='uq_user_tenant_roles_user_tenant_role'),
    schema='users_api'
    )
    op.create_index(op.f('ix_users_api_user_tenant_roles_role_id'), 'user_tenant_roles', ['role_id'], unique=False, schema='users_api')
    op.create_index(op.f('ix_users_api_user_tenant_roles_user_tenant_id'), 'user_tenant_roles', ['user_tenant_id'], unique=False, schema='users_api')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_api_user_tenant_roles_user_tenant_id'), table_name='user_tenant_roles', schema='users_api')
    op.drop_index(op.f('ix_users_api_user_tenant_roles_role_id'), table_name='user_tenant_roles', schema='users_api')
    op.drop_table('user_tenant_roles', schema='users_api')
    op.drop_index(op.f('ix_users_api_role_permissions_role_id'), table_name='role_permissions', schema='users_api')
    op.drop_index(op.f('ix_users_api_role_permissions_permission_id'), table_name='role_permissions', schema='users_api')
    op.drop_table('role_permissions', schema='users_api')
    op.drop_index(op.f('ix_users_api_roles_tenant_id'), table_name='roles', schema='users_api')
    op.drop_index(op.f('ix_users_api_roles_code'), table_name='roles', schema='users_api')
    op.drop_table('roles', schema='users_api')
    op.drop_index(op.f('ix_users_api_permissions_code'), table_name='permissions', schema='users_api')
    op.drop_table('permissions', schema='users_api')
    # ### end Alembic commands ###
