"""align cash register indexes with ORM models

Revision ID: d0e1f2a3b4c5
Revises: c9d8e7f6a5b4
Create Date: 2026-09-11
"""

from typing import Sequence, Union

from alembic import op

revision: str = "d0e1f2a3b4c5"
down_revision: Union[str, Sequence[str], None] = "c9d8e7f6a5b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SCHEMA = "users_api"


# These indexes are generated by SQLAlchemy's index=True on cash_register_id.
# The original traceability migration created tenant+cash_register composite
# indexes as well; those remain because they are explicitly declared by the
# ORM on the affected tables. This migration only reconciles the single-column
# indexes that Alembic check expects and removes the legacy portfolio index.
CASH_REGISTER_INDEXES = (
    ("inventory_movements", "ix_users_api_inventory_movements_cash_register_id"),
    ("obligations", "ix_users_api_obligations_cash_register_id"),
    ("portfolio_payments", "ix_users_api_portfolio_payments_cash_register_id"),
    ("sale_payments", "ix_users_api_sale_payments_cash_register_id"),
    ("sales", "ix_users_api_sales_cash_register_id"),
)


def upgrade() -> None:
    for table, index_name in CASH_REGISTER_INDEXES:
        op.create_index(
            index_name,
            table,
            ["cash_register_id"],
            unique=False,
            schema=SCHEMA,
        )

    op.drop_index(
        "ix_portfolio_payments_cash_register",
        table_name="portfolio_payments",
        schema=SCHEMA,
    )


def downgrade() -> None:
    op.create_index(
        "ix_portfolio_payments_cash_register",
        "portfolio_payments",
        ["tenant_id", "cash_register_id"],
        unique=False,
        schema=SCHEMA,
    )

    for table, index_name in reversed(CASH_REGISTER_INDEXES):
        op.drop_index(
            index_name,
            table_name=table,
            schema=SCHEMA,
        )
