"""remove obsolete user cash assignment unique constraint

Revision ID: ed6fe9b433af
Revises: a2b3c4d5e6f7
Create Date: 2026-09-10 00:07:50.254320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6fe9b433af'
down_revision: Union[str, Sequence[str], None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_cash_assignments_tenant_id'), 'user_cash_assignments', schema='users_api', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_cash_assignments_tenant_id'), 'user_cash_assignments', ['tenant_id', 'id'], schema='users_api', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
